<h3>The dojox/app Contacts Application Series</h3>
<div class="series">	
	<ol>
		<li><a href="/documentation/tutorials/1.9/dojox_app/contactsList/">Getting Started with dojox/app: Creating a simple Contacts List Application.</a></li>
		<li><a href="/documentation/tutorials/1.9/dojox_app/contactsPhone/">Creating a Contacts Application with a Phone form factor. Using two views, a "list" view and a "details" view.</a></li>
		<li><a href="/documentation/tutorials/1.9/dojox_app/contactsTablet/">Creating a Contacts Application with a Tablet or Phone form factor. Using two columns, a "list" view on the left
			and a "details" view in the center on a Tablet.</a></li>
		<li><a href="/documentation/tutorials/1.9/dojox_app/contactsCordova/">Updating the Contacts Application to use Cordova/PhoneGap for access to the contacts on a device, and building an application.</a></li>
	</ol>
</div>