In the previous tutorial, <a href="/documentation/tutorials/1.9/dojox_app/contactsTablet/">Creating a Contacts Application
with a tablet or phone form factor</a>, we updated the Contacts Application to use a tablet form factor in addition to the
phone form factor.  In this tutorial we will see how to use the dojox/app "Build" support,
and how to update the Contacts Application to use Cordova/PhoneGap based access the native contacts on a mobile device.